GaloisInc/pirate

- libpirate/primitives.c
- libpirate/primitives.h
- libpirate/tcp_socket.c
- libpirate/test/primitives_test.c
- libpirate/udp_socket.c
Add API to specify the port number for TCP and UDP channels. If port number is not specified then fallback to the default behavior of (26427 + d) where d is the gaps descriptor.
> libpirate: allow optional port numbers for TCP and UDP sockets

- .github/workflows/main.yml
- images/ubuntu/Dockerfile
This updates the Github action to build the pirateteam/ubuntu image and make it available.
> Build dockerhub image and artifacts.

- CMakeLists.txt
- libpirate/CMakeLists.txt
- libpirate/shmem_buffer.h
- libpirate/test/uio_test.cpp
- libpirate/uio.c
- libpirate/uio.h
- libpirate/uio_interface.c
- libpirate/uio_interface.h
Do not compile channel types that use atomic operations when atomic operations are not available.
> Move uio into the SHMEM_BUFFER optional compilation

- libpirate/ge_eth.c
- libpirate/tcp_socket.c
- libpirate/udp_socket.c
Bind the IP-based channels to a the ip address passed in as a parameter. This allows the reader to identify an attempt to bind to an address that cannot be assigned. Here is the error condition that is now detected by the channel demo:
```
./reader -l 10,20,1 -C ge_eth,169.254.0.1,8888 -v
[2020-03-16 15:17:13.198249] INFO Starting the reader
[2020-03-16 15:17:13.198598] ERR  Failed to open GAPS channel (Cannot assign requested address)
reader: Failed to initialize channel ge_eth,169.254.0.1,8888
```
> Replace INADDR_ANY with ip address parameter

- devices/cusegaps/cusegaps_net.c
- devices/cusegaps/cusegaps_pipe.c
- libpirate/ge_eth.c
- libpirate/mercury.c
- libpirate/pipe.c
- libpirate/shmem.c
- libpirate/tcp_socket.c
- libpirate/udp_shmem.c
- libpirate/udp_socket.c
- libpirate/unix_socket.c
When ignoring the error status of a system call, restore the previous value of errno. Do not reset the errno to 0.
> Restore errno instead of setting it to 0

- libpirate/ge_eth.c
- libpirate/libpirate.h
- libpirate/mercury.c
- libpirate/pipe.c
- libpirate/pipe.h
- libpirate/primitives.c
- libpirate/shmem.c
- libpirate/tcp_socket.c
- libpirate/test/channel_test.cpp
- libpirate/udp_shmem.c
- libpirate/udp_socket.c
- libpirate/uio.c
- libpirate/unix_socket.c
* Do not pthread_fork() to implement pirate_pipe_open(). Only support pirate_pipe_open() for a limited number of channel types that can be opened without spawning threads.
* Implement pirate_pipe_parse()
* Cleanup access mode usage. Preserve the remaining bits of the flags parameter.
> libpirate cleanup

- .github/workflows/main.yml
- CMakeLists.txt
- demos/CMakeLists.txt
- images/ubuntu/Dockerfile
- libpirate/CMakeLists.txt
This is intended to make the docker image demo build process self-contained.
It allows the demos to be configured and build independently of libpirate while still supporting an integrated scenario at the cost of some duplication.
It also updates the docker image build process to be in a separate task, and to test that the demos can be built prior to upload.
> Switch to use separate demos cmake files.

- demos/CMakeLists.txt
- libpirate/test/channel_test.cpp
- libpirate/test/channel_test.hpp
- libpirate/test/ge_eth_test.cpp
- libpirate/test/mercury_test.cpp
- libpirate/test/udp_socket_test.cpp
Use a barrier to ensure that the reader and writer threads have opened the channel. Use the barrier to ensure that each round of reading/writing has completed.
> Replace semaphore and sleep with pthread barrier

- libpirate/libpirate.h
- libpirate/primitives.c
Adds `int pirate_unparse_channel_param(const pirate_channel_param_t *param, char *str, int len)` to API to allow creating of description string for a parameter that is not associated with a gaps channel.
> Add libpirate API to unparse a pirate_channel_param_t

- demos/cxx_demo/reader.cpp
- demos/cxx_demo/writer.cpp
- demos/time_demo/src/sensor_manager.c
- demos/time_demo/src/signing_proxy.c
- demos/time_demo/src/signing_service.c
- demos/time_demo/src/video_sensor.c
- demos/time_demo/src/xwin_display.c
- libpirate/mercury_cntl.c
Apply syntax changes to silence older gcc warnings
> RHEL gcc fixes

- libpirate/mercury.c
In cases when no message ids are specified then send the level to the root device.
> Mercury use level instead of source id

- libpirate/bench/bench.py
- libpirate/bench/bench_lat1.c
- libpirate/bench/bench_lat2.c
- libpirate/bench/bench_lat_common.c
- libpirate/bench/bench_thr.h
- libpirate/bench/bench_thr_common.c
- libpirate/bench/bench_thr_reader.c
- libpirate/bench/bench_thr_writer.c
This branch has a few simplifications to the benchmarks.
On master, the benchmarks use one of the tests channels for both sending test data and an initial synchronization. This was a hack that I have replaced. I realized that the initial synchronization needed to be a two-way handshake. Originally, I did not want to insert a second synchronization channel. But that is the correct approach. Using the second sync channel eliminates the need for a signal_len and it stops using the buffer for both test data and synchronization data.
In the throughput benchmarks, sync channel 1 is opened with the same access mode as the test channel. Sync channel 2 is opened with the opposite access mode. In the latency benchmarks, sync channel 1 and test channel 1 are opened with the same access mode. Sync …
> WIP simplified benchmarks

- demos/channel_demo/README.md
- demos/channel_demo/src/writer.c
- libpirate/bench/README.md
- libpirate/bench/bench.py
- libpirate/bench/bench_lat.h
- libpirate/bench/bench_lat1.c
- libpirate/bench/bench_lat2.c
- libpirate/bench/bench_lat_common.c
- libpirate/bench/bench_thr.h
- libpirate/bench/bench_thr_common.c
- libpirate/bench/bench_thr_reader.c
- libpirate/bench/bench_thr_writer.c
Cleanup to the benchmarks and channel demo:
- backport the busysleep() into the channel demo. The timestamps printed in the channel demo (with -v) show that the write delays are more precise than using nanosleep().
- refactor the latency benchmark to use the command-line argument parsing
- removed the data validation from the latency benchmark. If we need it then I can add it again. The latency benchmark only sends one packet at a time. If a packet is dropped, then the latency demo will gracefully exit (unlike the throughput demo which reports a dropped packet and continues).
- added README to benchmarks
- better error handling in bench.py
> benchmark cleanup

- libpirate/device.c
- libpirate/ge_eth.c
- libpirate/mercury.c
- libpirate/pipe.c
- libpirate/serial.c
- libpirate/shmem.c
- libpirate/tcp_socket.c
- libpirate/test/common_test.cpp
- libpirate/udp_shmem.c
- libpirate/udp_socket.c
- libpirate/uio.c
- libpirate/unix_socket.c
This branch fixes an off-by-one error in calls to `snprintf` in the libpirate `*_get_channel_description` functions.
> Change `len - 1` to `len` in libpirate `*_get_channel_description`

- demos/word_filter/1.pal/CMakeLists.txt
- pal/include/pal/pal.h
Dummy resource sections must be empty in order to prevent the resource init functions from trying to read resource objects from uninitialized memory. This requires extensions, but should be OK for the time being, since the dummy resource sections can be removed once clang creates empty resource sections. Passing `-Wno-zero-length-array` can be used to silence warnings in conjunction with `-Wpedantic`.
> Make sure dummy resource sections are empty by default

- pal/CMakeLists.txt
Builds using Ninja as the generator were producing the following error:
`ninja: error: 'pal/libcyaml-1.0.2/lib/libcyaml.so', needed by 'pal/pal', missing and no known rule to make it`
Ninja is very picky about knowing where to find dependencies and needs to be informed that this library is a byproduct of the build in the external project.
See:
https://gitlab.kitware.com/cmake/cmake/commit/557aef0b94c86d13e802e6e8e34a491304d7be2f 
and
http://cmake.3232098.n2.nabble.com/ExternalProject-Add-static-library-Ninja-generator-td7590158.html
> Fix Ninja builds by declaring libcyaml.so as build byproduct

- libpirate/pirate_common.c
- libpirate/tcp_socket.c
- libpirate/test/channel_test.cpp
- libpirate/test/channel_test.hpp
- libpirate/test/pipe_test.cpp
- libpirate/test/tcp_socket_test.cpp
- libpirate/test/unix_socket_test.cpp
If the writer closes first then the reader receives a return value of 0 on the next read() request. If the reader closes first then the writer receives a SIGPIPE signal and an EPIPE errno on the next write() request. Add one set of shared unit tests to confirm same behavior across unix pipe, unix socket, and tcp socket. This behavior is only on connection-oriented channels.
On the tcp reader set socket option SO_LINGER to onoff=1 and linger=0. This causes the reader to send a RST packet and reset the connection on close(). Graceful TCP connection termination is two pairs of two-way FIN, ACK handshakes. Graceful termination would require the writer to read() and receive a return value of 0. Since a gaps writer must not call read() we use a RST packet sent from the reader to close the …
> Harmonize close() semantics on unix pipe, unix socket, and tcp socket

- libpirate/ge_eth.c
- libpirate/mercury.c
- libpirate/test/mercury_test.cpp
Fixes mtu ignored in pirate_mercury_get_channel_description and buffer overflow in pirate_mercury_get_channel_description. Adds unit tests for both cases. Closes #108. Closes #109.
> mercury channel description bugfixes

- demos/camera_demo/CMakeLists.txt
- demos/camera_demo/src/frameprocessorcreator.hpp
- demos/camera_demo/src/main.cpp
- demos/camera_demo/src/xwinframeprocessor.cpp
- demos/camera_demo/src/xwinframeprocessor.hpp
If libjpeg and libX11 are found by CMake then frames can be displayed in an X11 window instead of saving to the filesystem.
> Add XWindows frame processor to camera_demo

- demos/camera_demo/src/pantilt.hpp
This will avoid a C++ 11 deprecation warning (deprecated-copy)
> Remove standard PanTilt.operator=

- demos/camera_demo/README.md
- demos/camera_demo/src/colortracking.cpp
- demos/camera_demo/src/mpeg-ts-decoder.cpp
- demos/camera_demo/src/mpeg-ts-decoder.hpp
- demos/camera_demo/src/options.hpp
- demos/camera_demo/src/optionsparser.cpp
- demos/camera_demo/src/piservocameracontroloutput.cpp
- demos/camera_demo/src/piservocameracontroloutput.hpp
- demos/camera_demo/src/trilliumcontrol.cpp
- demos/camera_demo/src/trilliumcontrol.hpp
- demos/camera_demo/src/videosensor.cpp
- demos/camera_demo/src/videosensor.hpp
- demos/camera_demo/src/xwinframeprocessor.cpp
- demos/camera_demo/src/xwinframeprocessor.hpp
Use the command-line arguments to flip in the pi servo controller. Move the image flipping from the end of the pipeline to the
beginning of the pipeline. Simplify the command-line arguments use a single 'flip' argument to perform 180 degree rotation
(vertical flip and horizontal flip together).
> Bug fixes to camera flip

- antlr/CDRBuildTypes.cpp
- antlr/CDRBuildTypes.hpp
- antlr/CDRGenerator.cpp
- antlr/CDRTypes.cpp
- antlr/CDRTypes.hpp
- antlr/DFDLGenerator.cpp
- antlr/DFDLGenerator.hpp
- antlr/ModuleDecl.cpp
- antlr/ModuleDecl.hpp
- antlr/StructTypeSpec.cpp
- antlr/StructTypeSpec.hpp
- antlr/UnionTypeSpec.cpp
- antlr/UnionTypeSpec.hpp
Refactor the 'packed' boolean from a function parameter into a class field. The first implementation was quick and dirty and just passed around the 'packed' boolean wherever it was needed.
> idl refactor 'packed' from parameter into field

- vscode-plugins/architecture/.gitattributes
When this file changes, it makes large, uninteresting diffs.  This tells git
not to display those diffs.
> vscode-plugin: add .gitattributes for package-lock.json

- vscode-plugins/architecture/src/extension/parser.ts
- vscode-plugins/architecture/src/shared/architecture.ts
- vscode-plugins/architecture/src/webview/actor.ts
- vscode-plugins/architecture/src/webview/bus.ts
- vscode-plugins/architecture/src/webview/changeSet.ts
- vscode-plugins/architecture/src/webview/draggableRectangle.ts
- vscode-plugins/architecture/src/webview/geometry.ts
- vscode-plugins/architecture/src/webview/systemServices.ts
- vscode-plugins/architecture/src/webview/webview.ts
Beginning support for displaying buses.
Currently they display as red-filled rectangles, and support dragging around.
Due to the number of objects with collision, we will likely want to allow "jumping" over objects while dragging, but this can be a separate PR.
> vscode plug-in: display buses

- vscode-plugins/architecture/.eslintrc.json
- vscode-plugins/architecture/package-lock.json
- vscode-plugins/architecture/package.json
- vscode-plugins/architecture/src/extension/docUpdater.ts
- vscode-plugins/architecture/src/extension/lexer.ts
- vscode-plugins/architecture/src/extension/main.ts
- vscode-plugins/architecture/src/extension/modelResources.ts
- vscode-plugins/architecture/src/extension/modelWebview.ts
- vscode-plugins/architecture/src/extension/parser.ts
- vscode-plugins/architecture/src/shared/architecture.ts
- vscode-plugins/architecture/src/test/runTest.ts
- vscode-plugins/architecture/src/test/suite/extension.test.ts
- vscode-plugins/architecture/src/test/suite/index.ts
- vscode-plugins/architecture/src/webview/changeSet.ts
- vscode-plugins/architecture/src/webview/debugLog.ts
- vscode-plugins/architecture/src/webview/dragHandlers.ts
- vscode-plugins/architecture/src/webview/draggableRectangle.ts
- vscode-plugins/architecture/src/webview/svg.ts
- vscode-plugins/architecture/src/webview/systemServices.ts
- vscode-plugins/architecture/src/webview/views/actor.ts
- vscode-plugins/architecture/src/webview/views/bus.ts
- vscode-plugins/architecture/src/webview/webview.ts
This adds linting rules and fixes lots of linting problems, including:
- uniform string quotes,
- const over let,
- removes unused variables,
- favor isNaN for NaN comparison,
- missing return type annotations,
- avoid any where possible,
etc.
I also added some rules for making the imports more uniform.
> vscode plug-in: add aggressive linting

- libpirate/bench/bench.py
- libpirate/bench/bench_thr_reader.c
I tested bench.py locally and it appeared to be doing what I wanted it to do.
> libpirate throughput benchmark record packet rate

- vscode-plugins/architecture/README.md
- vscode-plugins/architecture/src/extension/modelResources.ts
- vscode-plugins/architecture/src/extension/modelWebview.ts
- vscode-plugins/architecture/src/shared/webviewProtocol.ts
- vscode-plugins/architecture/src/webview/webview.ts
This addresses a problem that occurs when the extension posts a model before the webview had registered a message event handler.
I also happened to update the readme.
> Architecture plugin: Add ready message from webview
